// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ms_parcela.Database;

#nullable disable

namespace msparcela.Migrations
{
    [DbContext(typeof(AuctionLandAPIContext))]
    [Migration("20230213164839_Fifth Migration")]
    partial class FifthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ms_parcela.Models.DeoParceleModel.DeoParcele", b =>
                {
                    b.Property<Guid>("deoParceleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("brojKatastraskaOpstina")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojParcele")
                        .HasColumnType("int");

                    b.Property<int>("povrsinaDelaParcele")
                        .HasColumnType("int");

                    b.Property<int>("redniBrojDelaParcele")
                        .HasColumnType("int");

                    b.HasKey("deoParceleID");

                    b.ToTable("DeoParceles");

                    b.HasData(
                        new
                        {
                            deoParceleID = new Guid("7cb99eda-bf52-4f8e-ad07-c9b7c05c7545"),
                            brojKatastraskaOpstina = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            brojParcele = 1,
                            povrsinaDelaParcele = 200,
                            redniBrojDelaParcele = 3
                        },
                        new
                        {
                            deoParceleID = new Guid("c70af8ce-56d9-404e-8233-57faf4fac26c"),
                            brojKatastraskaOpstina = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            brojParcele = 1,
                            povrsinaDelaParcele = 200,
                            redniBrojDelaParcele = 4
                        });
                });

            modelBuilder.Entity("ms_parcela.Models.KatastarskaOpstinaModel.KatastarskaOpstina", b =>
                {
                    b.Property<Guid>("brojKatastarskeOpstine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nazivKatastarskeOpstine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("brojKatastarskeOpstine");

                    b.ToTable("KatastarskaOpstinas");

                    b.HasData(
                        new
                        {
                            brojKatastarskeOpstine = new Guid("454fdd3f-958d-455c-974a-0b2bfbbfbc1f"),
                            nazivKatastarskeOpstine = "Cantavir"
                        },
                        new
                        {
                            brojKatastarskeOpstine = new Guid("cf62424e-c45f-439a-95c0-1c0eeb1128af"),
                            nazivKatastarskeOpstine = "Bajmok"
                        });
                });

            modelBuilder.Entity("ms_parcela.Models.ParcelaModel.Parcela", b =>
                {
                    b.Property<Guid>("brojKatastraskaOpstina")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojParcele")
                        .HasColumnType("int");

                    b.Property<string>("klasa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("kultura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("oblikSvojine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("obradivost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("odvodnjavanje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("povrsina")
                        .HasColumnType("int");

                    b.HasKey("brojKatastraskaOpstina", "brojParcele");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("ms_parcela.Models.ZonaModel.Zona", b =>
                {
                    b.Property<Guid>("zonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("brojZona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("zonaID");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            zonaID = new Guid("872e5dbd-85b5-4b27-babb-65a532b9c5f0"),
                            brojZona = "zona3"
                        },
                        new
                        {
                            zonaID = new Guid("64ef9a3b-bf2d-4999-be8c-857ab404efd1"),
                            brojZona = "zona4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
