// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ms_parcela.Database;

#nullable disable

namespace msparcela.Migrations
{
    [DbContext(typeof(AuctionLandAPIContext))]
    [Migration("20230210134858_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ms_parcela.Models.KatastarskaOpstinaModel.KatastarskaOpstina", b =>
                {
                    b.Property<Guid>("brojKatastarskeOpstine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nazivKatastarskeOpstine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("brojKatastarskeOpstine");

                    b.ToTable("KatastarskaOpstinas");

                    b.HasData(
                        new
                        {
                            brojKatastarskeOpstine = new Guid("8384f173-3e39-498d-b546-74fa71c427d4"),
                            nazivKatastarskeOpstine = "Cantavir"
                        },
                        new
                        {
                            brojKatastarskeOpstine = new Guid("f30ff623-1d7c-4d54-a119-aa21417db20f"),
                            nazivKatastarskeOpstine = "Bajmok"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
